services:
   palworld:
      image: thijsvanloef/palworld-server-docker
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PORT=8211
         - PUID=1000
         - PGID=1000
         - PLAYERS=16
         - MULTITHREADING=TRUE
         - COMMUNITY=FALSE  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
         # Enable the environment variables below if you have COMMUNITY=true
      #- SERVER_PASSWORD="papaya"
      #- SERVER_NAME="OnlyPals"
      # - ADMIN_PASSWORD="papaya_admin"
      volumes:
         - ./saves:/palworld/
